name: Release Pyrser
on:
  push:
    branches:
      - main
jobs:
  pypi-publish:
    name: python
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Install a specific version of uv.
          version: "0.5.1"
      - name: Publish
        run: |
          uv publish